# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-14 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproductivaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
