# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reproductivaApp', '0004_contenidosubcategoria_postcontenidosubcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontenidosubcategoria',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.ContenidoSubCategoria'),
        ),
    ]
