# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reproductivaApp', '0005_auto_20190914_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloguero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario_creo',
        ),
        migrations.AddField(
            model_name='post',
            name='bloguero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.Bloguero'),
            preserve_default=False,
        ),
    ]
