# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reproductivaApp', '0006_auto_20190914_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguero',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bloguero',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
