# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-21 04:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reproductivaApp', '0007_auto_20190915_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosPostContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('fecha_publicacion', models.DateField()),
                ('usuario', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.Estado')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.Post')),
            ],
        ),
    ]
