# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-21 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reproductivaApp', '0008_comentariospostcontenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariospostcontenido',
            name='id_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reproductivaApp.PostContenido'),
        ),
    ]
