# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-21 22:25
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reproductivaApp', '0009_auto_20190920_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='DudasFrecuentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', ckeditor.fields.RichTextField()),
                ('respuesta', ckeditor.fields.RichTextField()),
                ('fecha_publicacion', models.DateField()),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
