# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-25 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reproductivaApp', '0010_dudasfrecuentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='usuario_creo',
        ),
    ]
